# see config.toml.example for more possible options
  # See the 8.4 book for an old example using shipped LLVM
  # e.g. if not installing clang, or using a version before 13.0

  # Tell x.py the editors have reviewed the content of this file
  # and updated it to follow the major changes of the building system,
  # so x.py will not warn us to do such a review.
  change-id = 134650

  [llvm]
  # When using system llvm prefer shared libraries
  link-shared = true

  # Do not download pre-built LLVM, instead either use the system
  # LLVM or build LLVM from the shipped source.
  download-ci-llvm = false

  # If building the shipped LLVM source, only enable the x86 target
  # instead of all the targets supported by LLVM.
  targets = "X86"

  [build]
  # omit docs to save time and space (default is to build them)
  docs = false

  # install extended tools: cargo, clippy, etc
  extended = true

  # Do not query new versions of dependencies online.
  locked-deps = true

  # Specify which extended tools (those from the default install).
  tools = ["cargo", "clippy", "rustdoc", "rustfmt"]

  [install]
  prefix = "/opt/rustc-1.85.1"
  docdir = "share/doc/rustc-1.85.1"

  [rust]
  channel = "stable"
  description = "for BLFS r12.3-405"

  # Enable the same optimizations as the official upstream build.
  lto = "thin"
  codegen-units = 1

  [target.x86_64-unknown-linux-gnu]
  llvm-config = "/usr/bin/llvm-config"

  [target.i686-unknown-linux-gnu]
  llvm-config = "/usr/bin/llvm-config"